### ISSUE TITLE
GetFeatureInfo error ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wms-client13#8]
When performing the following request

```
http://localhost:8080/teamengine/monitor/14?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&BBOX=-0.13052631578947382,-6.97863157894736741,7.21947368421052715,8.30936842105263551&CRS=EPSG:4326&WIDTH=988&HEIGHT=475&LAYERS=cite:BuildingCenters&STYLES=&FORMAT=image/png&QUERY_LAYERS=cite:BuildingCenters&INFO_FORMAT=text/html&I=465&J=440&FEATURE_COUNT=10
```

The following error appears in the browser: 

```

HTTP Status 500 - java.lang.ArrayIndexOutOfBoundsException: 1

type Exception report

message java.lang.ArrayIndexOutOfBoundsException: 1

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: java.lang.ArrayIndexOutOfBoundsException: 1
        com.occamlab.te.web.MonitorServlet.process(MonitorServlet.java:262)
        com.occamlab.te.web.MonitorServlet.doGet(MonitorServlet.java:281)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

root cause

java.lang.ArrayIndexOutOfBoundsException: 1
        com.occamlab.te.web.CoverageMonitor.inspectQuery(CoverageMonitor.java:139)
        com.occamlab.te.web.MonitorCall.checkCoverage(MonitorCall.java:127)
        com.occamlab.te.web.MonitorServlet.process(MonitorServlet.java:163)
        com.occamlab.te.web.MonitorServlet.doGet(MonitorServlet.java:281)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.57 logs.

```

And in the catalina logs:

```
Mar 04, 2015 12:00:16 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [monitor] in context with path [/teamengine] threw exception [java.lang.ArrayIndexOutOfBoundsException: 1] with root cause
java.lang.ArrayIndexOutOfBoundsException: 1
    at com.occamlab.te.web.CoverageMonitor.inspectQuery(CoverageMonitor.java:139)
    at com.occamlab.te.web.MonitorCall.checkCoverage(MonitorCall.java:127)
    at com.occamlab.te.web.MonitorServlet.process(MonitorServlet.java:163)
    at com.occamlab.te.web.MonitorServlet.doGet(MonitorServlet.java:281)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by bermud** [comment]
Seems that is an issue with the reference implementation. 

The following request, 

```
http://cite.lat-lon.de/deegree-webservices-3.3.6-2/services/wms?SERVICE=WMS&INFO_FORMAT=text/html&LAYERS=cite:Autos&CRS=CRS:84&FORMAT=image/png&HEIGHT=400&J=145&REQUEST=GetFeatureInfo&I=315&WIDTH=549&BBOX=-5.171250000000001,-1.1225000000000005,4.436250000000001,5.8775&STYLES=default&QUERY_LAYERS=cite:Autos&VERSION=1.3.0
```

responds an HTML form

@segoerke, let us know is this is an issue with the ref implementation.

**Comment by ghost** [comment]
This is no issue. It is a valid getfeatureinfo output. HTML was requested and HTML was responded. There are no further requirements on GFI output...
There could or should be an enhancement for that within the RI, but still this is only an enhancement as WMS 1.3.0 specification requirements are met.

**Comment by bermud** [comment]
uDig is passing and confirmed with Sebastian that this is not an issue.
